### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by dsylex** [ma-ku/homebridge-elero-stick#1]
Hey any chance for an update on this one?

**Comment by ma-ku** [comment]
Well, I would not this consider an issue?! What is your particular need?

**Comment by dsylex** [comment]
> Well, I would not this consider an issue?! What is your particular need?

Sorry, you're right and I'm quite new to GitHub, so sorry if I've posted it in the wrong topic. Thing is, I've tried adding your plugin to Homebridge but I couldn't, I've pasted the logs below.

```npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated mkdirp@0.3.5: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated har-validator@5.1.5: this library is no longer supported

> @serialport/bindings@2.0.8 install /usr/local/lib/node_modules/homebridge-elero-stick/node_modules/@serialport/bindings
> prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild

prebuild-install WARN install EACCES: permission denied, open '/Users/sapi/.npm/_prebuilds/c2ab10-bindings-v2.0.8-node-v72-darwin-x64.tar.gz.1352-7dbc49276b50a.tmp'
No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 19.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/homebridge-elero-stick/node_modules/@serialport/bindings
gyp ERR! node -v v12.18.3
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @serialport/bindings@2.0.8 install: `prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @serialport/bindings@2.0.8 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by ma-ku** [comment]
OK, I can see this is on OS X 10.5. I will take a look. I am currently running this in a Docker container so probably there are some differences.

**Comment by dsylex** [comment]
> OK, I can see this is on OS X 10.5. I will take a look. I am currently running this in a Docker container so probably there are some differences.

Thanks a lot! I'll probably be migrating my setup to docker so if it works there, than it's a non-issue for me. Just wanted to check it out before I buy into a new NAS that's capable of running docker as also integrating my elero blinds into homekit would be one of the main reasons for that. Thanks a lot for your quick reply!

**Comment by ma-ku** [comment]
OK, long time but finally I had a chance to look into things.

(a) I updated the plugin to a more flexible structure and to use TypeScript instead of pure JS
(b) I start adding a few more features to the plugin such as reverse drives (swaps open/closed and so on)

Regarding your request. Most likely you just need to install Xcode to get this running as you apparently do not have a compiler and SDK on your system which is needed to compile the binary code behind the serialport library that is needed to communicate with the ELERO Stick.

**Comment by ma-ku** [comment]
I am currently updating the plugin. So please expect something with fresh dependencies coming out soon.
