### ISSUE TITLE
Which Stick is needed

### ISSUE THREAD

**Issue by Wurlitzer1971** [ma-ku/homebridge-elero-stick#14]
Hi Mathias,
Steffen here!
Which Stick I have to use for your Plugin?
I found two sticks...
I'm using 5 Zip-Rollos with elero wireless motors.
Best regards from germany / taunus :-)
Steffen

**Comment by ma-ku** [comment]
I found this stick at the following shops:

https://www.markisen-kauf.de/steuerung/fuer-rollladen-19/elero-rollladensteuerung/elero-funksteuerungen/elero-centero-transmitter-stick.html

https://www.band-berlin24.de/de/smart-home/elero-84/Centero-Transmitter-Stick-868.html

Good luck. It seems as if Elero has ceased the production in favor of a new product:
https://www.elero.de/de/anwendungen/anwendungsbeispiele/centero-home#c7592

**Comment by ma-ku** [comment]
AT a guess I would say were about the same age and live in the same region (FFM downtown).

**Comment by Wurlitzer1971** [comment]
I’m living near Frankfurt… Taunus!
✌️

**Comment by Wurlitzer1971** [comment]
Hey,
i'm thinking about to buy one of these (expensive) Transmitter - Sticks.
Can I see the status of the Elero motors (up or down)?

**Comment by ma-ku** [comment]
With the plugin you can control Elero motors for shutters and other systems. You can view the current status of the shutter as well as driving the shutter to a particular position (e.g. open 50%).

However, it is important to mention that the motors themselves are not reporting any percentages. That requires the plugin to monitor the motors and compute intermediation positions based on the running time off the motor and the total running time of the shutter. You can find a thorough explanation here: https://github.com/ma-ku/homebridge-elero-stick/issues/7#issuecomment-1259505374

**Comment by Wurlitzer1971** [comment]
Great!
I've ordered one transmitter stick!

**Comment by Wurlitzer1971** [comment]
Hey,
thank you!
Plugin works great in Homebridge.
I tried to install the plugin in HAM Adapter (iobroker). 1.30, but after installing it, the UI does not respond, after trying to open it.

**Comment by ma-ku** [comment]
Never tried this, actually I did not know that this option exists. However, if it does not respond, maybe a debug log could help. Is there a chance you can collect debug information?

**Comment by Wurlitzer1971** [comment]
There is an option to install version 1.01 and the UI is responding.

![image](https://user-images.githubusercontent.com/84268672/195325189-daf6b5b3-c857-4ab0-ac33-4471ea999e55.png)

**Comment by ma-ku** [comment]
Ah, that's interesting. I would need to check what is different between these versions. I would assume that the config.schema is maybe not compatible with the implementation on the HAM side? Can you add motors? What settings are displayed per motor?

**Comment by Wurlitzer1971** [comment]
Ahhh, it's not possible to add Motors... After clicking the safe button, there is no reaction. Doesn't work... :-(

**Comment by ma-ku** [comment]
I guess it is due to an outdated library in the HAM that is not able to handle the configuration schema. However, you can still edit the config manually.
