### ISSUE TITLE
more device classes

### ISSUE THREAD

**Issue by MiWi84** [ma-ku/homebridge-elero-stick#4]
Hi, 

is it possible to expand the plugin with more device classes?

The company Weinor use the elero system for their awnings, heaters and led lights.
For the awnings the plugin works great . 
But the heater switches on with up or down button and can also be dimmed in this way. It is switched off with the stop button.
The led lights work similarly.

I would be grateful for your feedback.

**Comment by ma-ku** [comment]
Well, 

apart from the fact that I am pretty busy these days, I would like to support this request. Question would be, how the Elero Stick would trigger these command sequences you described. Typically for an awning the motor is started in either direction and that's it. But for the heating it seems as if multiple up/down commands need to be sent?

**Comment by MiWi84** [comment]
Sorry, the holidays were also very stressful for me and I didn't get around to answering.
There are these functions with the remote control: 

### **led lights:**
holding up: dim brighter
stop: turn off
holding down: dim darker
double press up: highest light
**_double press down: highest light_**

### **heater:**
holding up: dim hotter
stop: turn off
holding down: dim cooler
double press up: highest temperature
**_double press down: lowest temperature_**

The only difference between heater and led lights is when the down button is pressed twice.

**Comment by ma-ku** [comment]
I have the ability in the plugin. However, these types need an implementation. I will eventually kick of development for the two types you have listed here. Maybe I can provide you something handy.

**Comment by ma-ku** [comment]
The issue that I see with these implementations is that apparently the devices are working like a dimmer but in HomeKit, everything has a value range. E.g. the heating has a min/max value and then these get assigned. Do you know if there is anything like that also applicable for these types of devices? I would then need to translate that information into the corresponding number of up/down commands.

In addition, it is worthwhile to see if the double press commands are translated into something different. I believe I have read somewhere that the elero shutters have a ventilation position that can be programmed and is then move to once you press down twice. The USB stick supports additional positions (intermediate position and ventilation position) but I have no idea, which devices support these positions and if the double press is actually sending that command?!

**Comment by ma-ku** [comment]
I have looked at the products and the potential implementation. While I believe that this is doable on the plugin side, I am wondering how you would like to use this in the Apple Home Application?

For the double up/down presses, I would assume you want some kind of button. But the Home App does not support push buttons, only switches. But in this case the switch would turn on and then flip back to off. Maybe you have a better idea?
